Add more log messages on backup job

diff --git a/k8s/templates/job-backup.yaml b/k8s/templates/job-backup.yaml
--- a/k8s/templates/job-backup.yaml
+++ b/k8s/templates/job-backup.yaml
@@ -32,7 +32,17 @@ spec:
                 if [[ ${exit_code} == 0 ]]; then 
                   find ${db_backups_path} -type f -mtime +{{ .Values.backup.retain_days }} -name '*.tar' -execdir rm -- '{}' \; ;
                   cp -urv /var/data/lm/* ${crate_backups_path}/ ;
+                  exit_code=$? ;
+                  if [[ ${exit_code} == 0 ]]; then 
+                    echo "RO-Crates locally synched @ ${crate_backups_path}" ;
+                  else echo "Error when copying RO-Crates (code ${exit_code})" ;
+                  fi ;
                   {{ include "backup.remote.command" . }} ;
+                  exit_code=$? ;
+                  if [[ ${exit_code} == 0 ]]; then 
+                    echo "Backup folder synched with the remote site '{{ .Values.backup.remote.host }}' (path {{.Values.backup.remote.path}})" ;
+                  else echo "Unable to synch backup folder with the remote site '{{ .Values.backup.remote.host }}'" ; exit ${exit_code} ;
+                  fi ;
                 else echo "Unable to complete the backup" ; exit ${exit_code} ; 
                 fi ;
             env:
